// AutoStockCollector-web/src/views/MarginTrading/index.vue
<template>
  <div class="margin-trading">
    <!-- Filters -->
    <el-card shadow="never" class="section-card">
      <div class="filter-bar">
        <el-date-picker
          v-model="dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          format="YYYY-MM-DD"
          value-format="YYYY-MM-DD"
          size="small"
          style="width:280px"
        />
        <el-button type="primary" size="small" @click="loadData">
          <el-icon><Search /></el-icon> 查询
        </el-button>
        <el-text size="small" type="info">融资融券为全市场汇总数据</el-text>
      </div>
    </el-card>

    <!-- Balance chart -->
    <el-card shadow="never" class="section-card" v-loading="loading">
      <template #header><span>融资余额趋势</span></template>
      <div v-if="chartData.length > 0">
        <v-chart :option="lineOption" style="height:300px" autoresize />
      </div>
      <el-empty v-else-if="!loading" description="暂无数据" :image-size="60" />
    </el-card>

    <!-- Table -->
    <el-card shadow="never" class="section-card" v-loading="loading">
      <template #header>
        <span>融资融券明细（共 {{ tableData.length }} 条）</span>
      </template>
      <el-empty v-if="tableData.length === 0 && !loading" description="暂无融资融券数据" />
      <el-table v-else :data="tableData" stripe size="small">
        <el-table-column prop="date" label="日期" width="120" sortable />
        <el-table-column label="融资余额" width="130" prop="rz_balance" sortable>
          <template #default="{ row }">{{ fmtAmount(row.rz_balance) }}</template>
        </el-table-column>
        <el-table-column label="融资买入" width="130" prop="rz_buy" sortable>
          <template #default="{ row }">{{ fmtAmount(row.rz_buy) }}</template>
        </el-table-column>
        <el-table-column label="融券量" width="120" prop="rq_volume" sortable>
          <template #default="{ row }">{{ fmtAmount(row.rq_volume) }}</template>
        </el-table-column>
        <el-table-column label="融券卖出" width="130" prop="rq_sell" sortable>
          <template #default="{ row }">{{ fmtAmount(row.rq_sell) }}</template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { LineChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent, DataZoomComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { marginApi } from '@/api/margin'
import { fmtAmount } from '@/utils/format'
import type { MarginRecord } from '@/types'
import { Search } from '@element-plus/icons-vue'
import dayjs from 'dayjs'

use([LineChart, GridComponent, TooltipComponent, LegendComponent, DataZoomComponent, CanvasRenderer])

const loading = ref(false)
const tableData = ref<MarginRecord[]>([])
const dateRange = ref<[string, string]>([
  dayjs().subtract(90, 'day').format('YYYY-MM-DD'),
  dayjs().format('YYYY-MM-DD'),
])

const chartData = computed(() => {
  return [...tableData.value].sort((a, b) => a.date.localeCompare(b.date)).slice(0, 60)
})

const lineOption = computed(() => {
  const sorted = chartData.value
  const dates = sorted.map(d => d.date)
  const balances = sorted.map(d => d.rz_balance)
  return {
    backgroundColor: '#1f1f1f',
    tooltip: {
      trigger: 'axis',
      backgroundColor: '#2c2c2c',
      borderColor: '#444',
      textStyle: { color: '#e5eaf3' },
    },
    grid: { left: 80, right: 20, top: 30, bottom: 40 },
    xAxis: {
      type: 'category',
      data: dates,
      axisLabel: { color: '#909399', rotate: 30, fontSize: 10 },
      axisLine: { lineStyle: { color: '#444' } },
    },
    yAxis: {
      type: 'value',
      axisLabel: {
        color: '#909399',
        formatter: (v: number) => (v >= 1e8 ? `${(v / 1e8).toFixed(1)}亿` : `${(v / 1e4).toFixed(0)}万`),
      },
      splitLine: { lineStyle: { color: '#2c2c2c' } },
    },
    series: [
      {
        name: '融资余额',
        type: 'line',
        data: balances,
        smooth: true,
        lineStyle: { color: '#409eff', width: 2 },
        areaStyle: { color: 'rgba(64,158,255,0.1)' },
        showSymbol: false,
      },
    ],
  }
})

async function loadData() {
  loading.value = true
  try {
    const params: { start_date?: string; end_date?: string; limit?: number } = {
      limit: 200,
    }
    if (dateRange.value) {
      params.start_date = dateRange.value[0]
      params.end_date = dateRange.value[1]
    }
    const res = await marginApi.getMargin(params)
    tableData.value = res.data?.data || res.data || []
  } catch {
    tableData.value = []
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.margin-trading {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section-card {
  background: #1f1f1f;
  border: 1px solid #2c2c2c;
}

.section-card :deep(.el-card__header) {
  border-bottom: 1px solid #2c2c2c;
  padding: 12px 16px;
  color: #e5eaf3;
  font-size: 14px;
  font-weight: 600;
}

.filter-bar {
  display: flex;
  gap: 12px;
  align-items: center;
  flex-wrap: wrap;
}
</style>

// AutoStockCollector-web/src/pages/MarginTrading/index.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { Card, Row, Col, Typography, DatePicker, Table, Spin, Empty } from 'antd';
import ReactECharts from 'echarts-for-react';
import dayjs from 'dayjs';
import { getMargin } from '@/api/margin';
import type { MarginRecord } from '@/types';
import { fmtAmount } from '@/utils/stockCode';
import StockSearch from '@/components/StockSearch';
import styles from './MarginTrading.module.css';

const { Title } = Typography;
const { RangePicker } = DatePicker;

const mockData: MarginRecord[] = [
  { code: 'SH600519', date: '2024-01-15', rz_balance: 285000000000, rz_buy: 15200000000, rq_volume: 1200000, rq_sell: 850000 },
  { code: 'SH601318', date: '2024-01-14', rz_balance: 198000000000, rz_buy: 9800000000, rq_volume: 2100000, rq_sell: 1800000 },
  { code: 'SH600036', date: '2024-01-13', rz_balance: 145000000000, rz_buy: 7600000000, rq_volume: 980000, rq_sell: 720000 },
  { code: 'SZ000001', date: '2024-01-12', rz_balance: 89000000000, rz_buy: 4500000000, rq_volume: 560000, rq_sell: 420000 },
  { code: 'SZ300750', date: '2024-01-11', rz_balance: 168000000000, rz_buy: 11200000000, rq_volume: 1800000, rq_sell: 1450000 },
];

export default function MarginTrading() {
  const [data, setData] = useState<MarginRecord[]>([]);
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs, dayjs.Dayjs]>([
    dayjs().subtract(30, 'day'),
    dayjs(),
  ]);
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getMargin({
        start_date: dateRange[0].format('YYYY-MM-DD'),
        end_date: dateRange[1].format('YYYY-MM-DD'),
        code: code || undefined,
      });
      const resData = res as unknown as { data?: MarginRecord[] };
      if (resData?.data && Array.isArray(resData.data)) {
        setData(resData.data);
      } else {
        setData(mockData);
      }
    } catch {
      setData(mockData);
    } finally {
      setLoading(false);
    }
  }, [dateRange, code]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleStockSelect = (selectedCode: string) => {
    setCode(selectedCode);
  };

  const chartOption = {
    backgroundColor: 'transparent',
    tooltip: { trigger: 'axis' },
    legend: { data: ['融资余额', '融资买入额'], textStyle: { color: '#8c8c8c' } },
    grid: { left: 60, right: 20, top: 40, bottom: 40 },
    xAxis: { type: 'category', data: data.map(d => d.date), axisLine: { lineStyle: { color: '#303030' } }, axisLabel: { color: '#8c8c8c' } },
    yAxis: { type: 'value', axisLine: { lineStyle: { color: '#303030' } }, axisLabel: { color: '#8c8c8c', formatter: (v: number) => fmtAmount(v) }, splitLine: { lineStyle: { color: '#262626' } } },
    series: [
      { name: '融资余额', type: 'line', data: data.map(d => d.rz_balance), smooth: true, lineStyle: { color: '#ef5350' }, itemStyle: { color: '#ef5350' } },
      { name: '融资买入额', type: 'line', data: data.map(d => d.rz_buy), smooth: true, lineStyle: { color: '#26a69a' }, itemStyle: { color: '#26a69a' } },
    ],
  };

  const columns = [
    { title: '股票代码', dataIndex: 'code', key: 'code', width: 100 },
    { title: '日期', dataIndex: 'date', key: 'date', width: 120 },
    { title: '融资余额', dataIndex: 'rz_balance', key: 'rz_balance', render: (v: number) => fmtAmount(v) },
    { title: '融资买入额', dataIndex: 'rz_buy', key: 'rz_buy', render: (v: number) => fmtAmount(v) },
    { title: '融券余量', dataIndex: 'rq_volume', key: 'rq_volume', render: (v: number) => fmtAmount(v) },
    { title: '融券卖出量', dataIndex: 'rq_sell', key: 'rq_sell', render: (v: number) => fmtAmount(v) },
  ];

  return (
    <div className={styles.container}>
      <Title level={3} style={{ color: '#fff', marginBottom: 16 }}>融资融券</Title>

      <Card className={styles.filterCard}>
        <Row gutter={16} align="middle">
          <Col>
            <span style={{ color: '#8c8c8c', marginRight: 8 }}>日期范围：</span>
            <RangePicker 
              value={dateRange} 
              onChange={(dates) => dates && setDateRange([dates[0]!, dates[1]!])} 
            />
          </Col>
          <Col>
            <StockSearch placeholder="筛选股票代码" onSelect={handleStockSelect} />
          </Col>
        </Row>
      </Card>

      <Card className={styles.chartCard} title="融资余额趋势">
        {loading ? (
          <div style={{ textAlign: 'center', padding: 50 }}>
            <Spin />
          </div>
        ) : data.length > 0 ? (
          <ReactECharts option={chartOption} style={{ height: 300 }} />
        ) : (
          <Empty description="暂无数据" />
        )}
      </Card>

      <Card className={styles.tableCard}>
        <Table
          columns={columns}
          dataSource={data.map(d => ({ ...d, key: `${d.code}-${d.date}` }))}
          pagination={{ pageSize: 10 }}
          size="small"
        />
      </Card>
    </div>
  );
}
