// AutoStockCollector-web/src/components/ProgressTable/index.vue
<template>
  <el-table :data="data" stripe style="width: 100%" v-loading="loading">
    <el-table-column prop="task_type" label="任务类型" width="160">
      <template #default="{ row }">
        <el-tag size="small" type="info">{{ taskTypeLabel(row.task_type) }}</el-tag>
      </template>
    </el-table-column>
    <el-table-column label="进度" min-width="200">
      <template #default="{ row }">
        <el-progress
          :percentage="calcPercent(row)"
          :status="progressStatus(row)"
          :stroke-width="8"
          :format="() => `${row.progress || row.success || 0}/${row.total || 0}`"
        />
      </template>
    </el-table-column>
    <el-table-column prop="success" label="成功" width="80" align="center">
      <template #default="{ row }">
        <span class="text-success">{{ row.success || 0 }}</span>
      </template>
    </el-table-column>
    <el-table-column prop="failed" label="失败" width="80" align="center">
      <template #default="{ row }">
        <span :class="row.failed > 0 ? 'text-danger' : 'text-muted'">{{ row.failed || 0 }}</span>
      </template>
    </el-table-column>
    <el-table-column label="状态" width="100" align="center">
      <template #default="{ row }">
        <el-badge
          :type="badgeType(row)"
          :value="badgeLabel(row)"
          :max="9999"
        />
      </template>
    </el-table-column>
    <el-table-column label="耗时" width="90" align="center">
      <template #default="{ row }">
        <span class="text-muted">{{ row.elapsed_time ? `${row.elapsed_time}s` : '--' }}</span>
      </template>
    </el-table-column>
  </el-table>
</template>

<script setup lang="ts">
import type { CollectProgress } from '@/types'
import { fmtDateTime } from '@/utils/format'

interface Props {
  data: CollectProgress[]
  loading?: boolean
}

defineProps<Props>()

const TASK_TYPE_LABELS: Record<string, string> = {
  kline: 'K线数据',
  financial: '财务数据',
  news: '新闻资讯',
  fund_flow: '资金流向',
  dragon_tiger: '龙虎榜',
  margin: '融资融券',
  sector: '板块数据',
  stock_info: '股票信息',
}

function taskTypeLabel(type: string): string {
  return TASK_TYPE_LABELS[type] || type
}

function calcPercent(row: CollectProgress): number {
  if (row.percent !== undefined && row.percent > 0) return Math.min(100, Math.round(row.percent))
  if (!row.total || row.total === 0) return 0
  return Math.min(100, Math.round(((row.progress || row.success || 0) / row.total) * 100))
}

function progressStatus(row: CollectProgress): '' | 'success' | 'exception' | 'warning' {
  const pct = calcPercent(row)
  if (pct === 100) return 'success'
  if (row.failed > 0 && row.failed > (row.success || 0)) return 'exception'
  if (pct > 0) return ''
  return ''
}

function badgeType(row: CollectProgress): 'success' | 'danger' | 'warning' | 'info' | 'primary' {
  if (row.status === 'completed') return 'success'
  if (row.status === 'failed') return 'danger'
  if (row.status === 'running') return 'primary'
  if (row.status === 'cancelled') return 'warning'
  return 'info'
}

function badgeLabel(row: CollectProgress): string {
  const labels: Record<string, string> = {
    completed: '完成', failed: '失败', running: '进行中',
    cancelled: '取消', pending: '等待', not_started: '未开始',
  }
  return labels[row.status] || row.status || '未开始'
}
</script>

<style scoped>
.text-success {
  color: #67c23a;
}
.text-danger {
  color: #f56c6c;
}
.text-muted {
  color: #909399;
  font-size: 12px;
}
</style>

// AutoStockCollector-web/src/components/ProgressTable/index.tsx
import React from 'react';
import { Table, Tag, Progress, Badge } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import type { TaskProgress } from '@/types';
import { formatDuration } from '@/utils/stockCode';

const typeNameMap: Record<string, string> = {
  kline: 'K线数据',
  stock_info: '股票基础信息',
  financial: '财务数据',
  news: '新闻舆情',
  fund_flow: '资金流向',
  dragon_tiger: '龙虎榜',
  block: '板块数据',
  margin_data: '融资融券',
};

const statusMap: Record<string, { color: string; text: string }> = {
  completed: { color: 'success', text: '已完成' },
  running: { color: 'processing', text: '采集中' },
  pending: { color: 'default', text: '等待中' },
  failed: { color: 'error', text: '失败' },
  cancelled: { color: 'warning', text: '已取消' },
};

interface ProgressTableProps {
  data: TaskProgress[];
  loading?: boolean;
}

export default function ProgressTable({ data, loading }: ProgressTableProps) {
  const columns: ColumnsType<TaskProgress> = [
    {
      title: '数据类型',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => typeNameMap[type] || type,
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => {
        const s = statusMap[status] || { color: 'default', text: status };
        return <Badge status={s.color as 'success' | 'processing' | 'default' | 'error' | 'warning'} text={s.text} />;
      },
    },
    {
      title: '进度',
      dataIndex: 'progress',
      key: 'progress',
      width: 200,
      render: (progress: number, record: TaskProgress) => (
        <Progress
          percent={record.total > 0 ? Math.round((progress / record.total) * 100) : 0}
          status={record.status === 'failed' ? 'exception' : undefined}
          format={() => `${progress}/${record.total}`}
        />
      ),
    },
    {
      title: '成功',
      dataIndex: 'success',
      key: 'success',
      width: 80,
      render: (v: number) => <Tag color="green">{v}</Tag>,
    },
    {
      title: '失败',
      dataIndex: 'failed',
      key: 'failed',
      width: 80,
      render: (v: number) => (v > 0 ? <Tag color="red">{v}</Tag> : <span>0</span>),
    },
    {
      title: '耗时',
      dataIndex: 'duration',
      key: 'duration',
      width: 100,
      render: (d: number) => formatDuration(d),
    },
  ];

  return (
    <Table
      columns={columns}
      dataSource={data.map((item) => ({ ...item, key: item.type }))}
      loading={loading}
      pagination={false}
      size="small"
    />
  );
}
