// AutoStockCollector-web/src/views/StockDetail/index.vue
<template>
  <div class="stock-detail">
    <!-- Search -->
    <el-card shadow="never" class="section-card">
      <div class="search-bar">
        <StockSearch v-model="currentCode" @search="loadStock" />
        <span v-if="currentCode" class="current-code">当前：{{ currentCode }}</span>
      </div>
    </el-card>

    <div v-if="!currentCode" class="empty-hint">
      <el-empty description="请输入股票代码查询详情" />
    </div>

    <template v-else>
      <!-- Stock info -->
      <el-card shadow="never" class="section-card" v-loading="infoLoading">
        <template #header><span>基础信息</span></template>
        <div v-if="stockInfo" class="info-grid">
          <div class="info-item">
            <span class="info-label">代码</span>
            <span class="info-value">{{ stockInfo.code }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">名称</span>
            <span class="info-value">{{ stockInfo.name || '--' }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">行业</span>
            <span class="info-value">{{ stockInfo.industry || '--' }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">地区</span>
            <span class="info-value">{{ stockInfo.area || '--' }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">市盈率PE</span>
            <span class="info-value">{{ fmtNumber(stockInfo.pe) }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">市净率PB</span>
            <span class="info-value">{{ fmtNumber(stockInfo.pb) }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">总市值</span>
            <span class="info-value">{{ fmtAmount(stockInfo.total_mv || 0) }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">上市日期</span>
            <span class="info-value">{{ stockInfo.list_date || '--' }}</span>
          </div>
        </div>
        <el-empty v-else-if="!infoLoading" description="暂无基础信息" :image-size="60" />
      </el-card>

      <!-- K-line chart -->
      <el-card shadow="never" class="section-card" v-loading="klineLoading">
        <template #header>
          <div class="card-header">
            <span>K线图</span>
            <div class="date-filter">
              <el-date-picker
                v-model="klineDateRange"
                type="daterange"
                range-separator="至"
                start-placeholder="开始日期"
                end-placeholder="结束日期"
                format="YYYY年MM月DD日"
                value-format="YYYY-MM-DD"
                size="small"
                style="width:280px"
                @change="loadKline"
              />
            </div>
          </div>
        </template>
        <KlineChart v-if="klineData.length > 0" :data="klineData" chart-height="480px" />
        <el-empty v-else-if="!klineLoading" description="暂无K线数据" :image-size="60" />
      </el-card>

      <!-- Financial data -->
      <el-card shadow="never" class="section-card" v-loading="financialLoading">
        <template #header><span>财务数据</span></template>
        <el-empty v-if="financialList.length === 0 && !financialLoading" description="暂无财务数据" :image-size="60" />
        <el-table v-else :data="financialList" stripe size="small">
          <el-table-column prop="report_date" label="报告期" width="120" />
          <el-table-column label="净利润" width="120">
            <template #default="{ row }">{{ fmtAmount(row.net_profit) }}</template>
          </el-table-column>
          <el-table-column label="营业收入" width="120">
            <template #default="{ row }">{{ fmtAmount(row.revenue) }}</template>
          </el-table-column>
          <el-table-column label="ROE" width="100">
            <template #default="{ row }">{{ fmtNumber(row.roe) }}%</template>
          </el-table-column>
          <el-table-column label="ROA" width="100">
            <template #default="{ row }">{{ fmtNumber(row.roa) }}%</template>
          </el-table-column>
          <el-table-column label="EPS" width="100">
            <template #default="{ row }">{{ fmtNumber(row.eps) }}</template>
          </el-table-column>
          <el-table-column label="BPS" width="100">
            <template #default="{ row }">{{ fmtNumber(row.bps) }}</template>
          </el-table-column>
        </el-table>
      </el-card>

      <!-- News -->
      <el-card shadow="never" class="section-card" v-loading="newsLoading">
        <template #header><span>相关新闻</span></template>
        <div v-if="newsList.length === 0 && !newsLoading" class="empty-state">
          <el-empty description="暂无相关新闻" :image-size="60" />
        </div>
        <div v-else class="news-list">
          <div v-for="(news, idx) in newsList" :key="idx" class="news-item">
            <div class="news-title">{{ news.title }}</div>
            <div class="news-meta">
              <span>{{ fmtDateTime(news.publish_date || news.datetime || news.date) }}</span>
              <span v-if="news.source" class="news-source">{{ news.source }}</span>
            </div>
          </div>
        </div>
      </el-card>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import StockSearch from '@/components/StockSearch/index.vue'
import KlineChart from '@/components/KlineChart/index.vue'
import { stockApi } from '@/api/stock'
import { klineApi } from '@/api/kline'
import { financialApi } from '@/api/financial'
import { newsApi } from '@/api/news'
import { fmtAmount, fmtDateTime, fmtNumber } from '@/utils/format'
import type { StockInfo, KlineRecord, FinancialRecord, NewsRecord } from '@/types'
import dayjs from 'dayjs'

const route = useRoute()

const currentCode = ref((route.query.code as string) || '')
const infoLoading = ref(false)
const klineLoading = ref(false)
const financialLoading = ref(false)
const newsLoading = ref(false)

const stockInfo = ref<StockInfo | null>(null)
const klineData = ref<KlineRecord[]>([])
const financialList = ref<FinancialRecord[]>([])
const newsList = ref<NewsRecord[]>([])
const klineDateRange = ref<[string, string]>([
  dayjs().subtract(1, 'year').format('YYYY-MM-DD'),
  dayjs().format('YYYY-MM-DD'),
])

async function loadStock(code: string) {
  if (!code) return
  currentCode.value = code
  await Promise.all([
    loadInfo(),
    loadKline(),
    loadFinancial(),
    loadNews(),
  ])
}

async function loadInfo() {
  infoLoading.value = true
  try {
    const res = await stockApi.getStockInfo(currentCode.value)
    const raw = res.data?.data || res.data || null
    if (raw) {
      // 后端返回中文字段，统一映射为英文
      stockInfo.value = {
        code: raw.code || currentCode.value,
        name: raw.name || raw['A股简称'] || raw['公司名称'] || '--',
        industry: raw.industry || raw['所属行业'] || '--',
        area: raw.area || raw['注册地址'] || raw['办公地址'] || '--',
        pe: raw.pe ?? raw['市盈率'] ?? null,
        pb: raw.pb ?? raw['市净率'] ?? null,
        total_mv: raw.total_mv || raw['注册资金'] || 0,
        list_date: raw.list_date || raw['上市日期'] || '--',
        market: raw.market || raw['所属市场'] || '--',
        ...raw,
      } as StockInfo
    } else {
      stockInfo.value = null
    }
  } catch {
    stockInfo.value = null
  } finally {
    infoLoading.value = false
  }
}

async function loadKline() {
  klineLoading.value = true
  try {
    const params: { start_date?: string; end_date?: string } = {}
    if (klineDateRange.value) {
      params.start_date = klineDateRange.value[0]
      params.end_date = klineDateRange.value[1]
    }
    const res = await klineApi.getKline(currentCode.value, params)
    klineData.value = res.data?.data || res.data || []
  } catch {
    klineData.value = []
  } finally {
    klineLoading.value = false
  }
}

async function loadFinancial() {
  financialLoading.value = true
  try {
    const res = await financialApi.getFinancial(currentCode.value)
    const data = res.data?.data || res.data || []
    financialList.value = Array.isArray(data) ? data : [data]
  } catch {
    financialList.value = []
  } finally {
    financialLoading.value = false
  }
}

async function loadNews() {
  newsLoading.value = true
  try {
    const res = await newsApi.getNews({ code: currentCode.value, limit: 10 })
    const data = res.data?.data || res.data || []
    newsList.value = Array.isArray(data) ? data : []
  } catch {
    newsList.value = []
  } finally {
    newsLoading.value = false
  }
}

// Reload when navigating to a different stock code without unmounting the component
watch(() => route.query.code, (code) => {
  if (code && code !== currentCode.value) {
    currentCode.value = code as string
    loadStock(code as string)
  }
})

onMounted(() => {
  if (currentCode.value) {
    loadStock(currentCode.value)
  }
})
</script>

<style scoped>
.stock-detail {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.section-card {
  background: #1f1f1f;
  border: 1px solid #2c2c2c;
}

.section-card :deep(.el-card__header) {
  border-bottom: 1px solid #2c2c2c;
  padding: 12px 16px;
  color: #e5eaf3;
  font-size: 14px;
  font-weight: 600;
}

.search-bar {
  display: flex;
  align-items: center;
  gap: 16px;
}

.current-code {
  color: #909399;
  font-size: 13px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.info-label {
  font-size: 12px;
  color: #606266;
}

.info-value {
  font-size: 14px;
  color: #e5eaf3;
  font-weight: 500;
}

.news-list {
  display: flex;
  flex-direction: column;
}

.news-item {
  padding: 10px 0;
  border-bottom: 1px solid #2c2c2c;
}

.news-item:last-child {
  border-bottom: none;
}

.news-title {
  font-size: 13px;
  color: #e5eaf3;
  line-height: 1.4;
  margin-bottom: 4px;
}

.news-meta {
  display: flex;
  gap: 12px;
  font-size: 11px;
  color: #606266;
}

.news-source {
  color: #909399;
}

.empty-hint {
  display: flex;
  justify-content: center;
  padding: 60px 0;
}

.empty-state {
  padding: 20px 0;
}
</style>

// AutoStockCollector-web/src/pages/StockDetail/index.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { Card, Row, Col, Typography, DatePicker, Descriptions, Table, Tabs, Spin, message, Empty, Alert } from 'antd';
import { LoadingOutlined } from '@ant-design/icons';
import { getKline, getLatestKline } from '@/api/kline';
import { getStockInfo } from '@/api/stock';
import { getFinancial } from '@/api/financial';
import { getFundFlow } from '@/api/fundFlow';
import { getNews } from '@/api/news';
import type { KlineRecord, StockInfo, FinancialRecord, NewsItem, FundFlowRecord } from '@/types';
import { fmtAmount, fmtPercent, RISE_COLOR, FALL_COLOR, normalizeCode } from '@/utils/stockCode';
import KlineChart from '@/components/KlineChart';
import StockSearch from '@/components/StockSearch';
import styles from './StockDetail.module.css';
import dayjs from 'dayjs';

const { Title } = Typography;
const { RangePicker } = DatePicker;

export default function StockDetail() {
  const { code: urlCode } = useParams<{ code: string }>();
  const [searchParams] = useSearchParams();
  const [code, setCode] = useState(urlCode || '');
  const [klineData, setKlineData] = useState<KlineRecord[]>([]);
  const [stockInfo, setStockInfo] = useState<StockInfo | null>(null);
  const [financialData, setFinancialData] = useState<FinancialRecord[]>([]);
  const [fundFlowData, setFundFlowData] = useState<FundFlowRecord[]>([]);
  const [newsData, setNewsData] = useState<NewsItem[]>([]);
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs, dayjs.Dayjs]>([
    dayjs().subtract(1, 'year'),
    dayjs(),
  ]);
  const [loading, setLoading] = useState(false);
  const [latestKline, setLatestKline] = useState<KlineRecord | null>(null);
  const [hasError, setHasError] = useState(false);

  const fetchData = useCallback(async (stockCode: string) => {
    if (!stockCode) return;
    setLoading(true);
    setHasError(false);
    
    try {
      const results = await Promise.allSettled([
        getKline(stockCode, {
          start_date: dateRange[0].format('YYYY-MM-DD'),
          end_date: dateRange[1].format('YYYY-MM-DD'),
        }),
        getStockInfo(stockCode),
        getFinancial(stockCode),
        getFundFlow(stockCode),
        getNews({ code: stockCode, limit: 20 }),
        getLatestKline(stockCode),
      ]);

      const [klineRes, infoRes, financialRes, fundFlowRes, newsRes, latestRes] = results;

      if (klineRes.status === 'fulfilled' && Array.isArray(klineRes.value)) {
        setKlineData(klineRes.value);
      }

      if (infoRes.status === 'fulfilled' && infoRes.value?.data) {
        setStockInfo(infoRes.value.data);
      }

      if (financialRes.status === 'fulfilled' && Array.isArray(financialRes.value)) {
        setFinancialData(financialRes.value);
      }

      if (fundFlowRes.status === 'fulfilled' && Array.isArray(fundFlowRes.value)) {
        setFundFlowData(fundFlowRes.value);
      }

      if (newsRes.status === 'fulfilled' && newsRes.value?.data && Array.isArray(newsRes.value.data)) {
        setNewsData(newsRes.value.data);
      }

      if (latestRes.status === 'fulfilled' && latestRes.value?.data) {
        setLatestKline(latestRes.value.data);
      }
    } catch (err) {
      console.error('Failed to fetch stock data:', err);
      setHasError(true);
      message.error('获取股票数据失败');
    } finally {
      setLoading(false);
    }
  }, [dateRange]);

  useEffect(() => {
    if (code) {
      fetchData(code);
    }
  }, [code, fetchData]);

  useEffect(() => {
    const codeParam = searchParams.get('code');
    if (codeParam) {
      setCode(normalizeCode(codeParam));
    }
  }, [searchParams]);

  const handleStockSelect = (selectedCode: string) => {
    setCode(selectedCode);
  };

  const financialColumns = [
    { title: '报告期', dataIndex: 'report_date', key: 'report_date' },
    { title: '营业收入', dataIndex: 'revenue', key: 'revenue', render: (v: number) => v ? fmtAmount(v) : '-' },
    { title: '净利润', dataIndex: 'net_profit', key: 'net_profit', render: (v: number) => v ? fmtAmount(v) : '-' },
    { title: '每股收益', dataIndex: 'eps', key: 'eps', render: (v: number) => v?.toFixed(2) || '-' },
    { title: 'ROE', dataIndex: 'roe', key: 'roe', render: (v: number) => v ? `${v.toFixed(2)}%` : '-' },
    { title: '净资产', dataIndex: 'net_asset', key: 'net_asset', render: (v: number) => v ? fmtAmount(v) : '-' },
  ];

  const fundFlowColumns = [
    { title: '日期', dataIndex: 'date', key: 'date' },
    { title: '成交量', dataIndex: 'volume', key: 'volume', render: (v: number) => v ? fmtAmount(v) : '-' },
    { title: '成交额', dataIndex: 'amount', key: 'amount', render: (v: number) => v ? fmtAmount(v) : '-' },
    { title: '方向', dataIndex: 'direction', key: 'direction', render: (d: string) => d === 'buy' ? '买入' : '卖出' },
    { title: '价格', dataIndex: 'price', key: 'price', render: (v: number) => v ? `¥${v.toFixed(2)}` : '-' },
  ];

  const newsColumns = [
    { title: '时间', dataIndex: 'publish_time', key: 'publish_time', width: 120, 
      render: (t: string) => t ? new Date(t).toLocaleDateString('zh-CN') : '-' },
    { title: '标题', dataIndex: 'title', key: 'title', 
      render: (t: string, r: NewsItem) => t ? <a href={r.url} target="_blank" rel="noopener noreferrer">{t}</a> : '-' },
    { title: '来源', dataIndex: 'source', key: 'source', width: 100 },
  ];

  const renderLoading = () => (
    <div style={{ textAlign: 'center', padding: 50 }}>
      <Spin indicator={<LoadingOutlined style={{ fontSize: 48 }} spin />} />
    </div>
  );

  const renderEmpty = (message: string) => (
    <Empty description={message} style={{ padding: 50 }} />
  );

  const tabItems = [
    { 
      key: 'financial', 
      label: '财务数据', 
      children: financialData.length > 0 ? (
        <Table 
          columns={financialColumns} 
          dataSource={financialData.map(d => ({ ...d, key: d.report_date }))} 
          pagination={false} 
          size="small" 
        />
      ) : renderEmpty('暂无财务数据')
    },
    { 
      key: 'fundflow', 
      label: '资金流向', 
      children: fundFlowData.length > 0 ? (
        <Table 
          columns={fundFlowColumns} 
          dataSource={fundFlowData.map(d => ({ ...d, key: `${d.date}-${d.direction}` }))} 
          pagination={false} 
          size="small" 
        />
      ) : renderEmpty('暂无资金流向数据')
    },
    { 
      key: 'news', 
      label: '相关新闻', 
      children: newsData.length > 0 ? (
        <Table 
          columns={newsColumns} 
          dataSource={newsData.map(d => ({ ...d, key: d.id }))} 
          pagination={false} 
          size="small" 
        />
      ) : renderEmpty('暂无相关新闻')
    },
  ];

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Title level={3} style={{ color: '#fff', margin: 0 }}>股票详情</Title>
        <StockSearch onSelect={handleStockSelect} />
      </div>

      {code && latestKline && (
        <Alert
          message={
            <Row gutter={16} align="middle">
              <Col>
                <span className={styles.stockName}>{stockInfo?.name || code}</span>
              </Col>
              <Col>
                <span className={styles.price} style={{ color: latestKline.change_rate >= 0 ? RISE_COLOR : FALL_COLOR }}>
                  {latestKline.close.toFixed(2)}
                </span>
              </Col>
              <Col>
                <span style={{ color: latestKline.change_rate >= 0 ? RISE_COLOR : FALL_COLOR, fontSize: 18 }}>
                  {fmtPercent(latestKline.change_rate)}
                </span>
              </Col>
            </Row>
          }
          type="none"
          style={{ background: '#1a1a1a', border: '1px solid #303030' }}
        />
      )}

      <Card className={styles.infoCard}>
        <Descriptions column={3} size="small">
          <Descriptions.Item label="股票代码">{code || '-'}</Descriptions.Item>
          <Descriptions.Item label="市场">{stockInfo?.market || '-'}</Descriptions.Item>
          <Descriptions.Item label="行业">{stockInfo?.industry || '-'}</Descriptions.Item>
          <Descriptions.Item label="上市日期">{stockInfo?.list_date || '-'}</Descriptions.Item>
          <Descriptions.Item label="总股本">{stockInfo?.total_share ? fmtAmount(stockInfo.total_share) : '-'}</Descriptions.Item>
          <Descriptions.Item label="流通股本">{stockInfo?.float_share ? fmtAmount(stockInfo.float_share) : '-'}</Descriptions.Item>
        </Descriptions>
      </Card>

      <Card 
        className={styles.chartCard}
        title="K线走势"
        extra={
          <RangePicker 
            value={dateRange} 
            onChange={(dates) => dates && setDateRange([dates[0]!, dates[1]!])} 
          />
        }
      >
        {loading ? (
          renderLoading()
        ) : klineData.length > 0 ? (
          <KlineChart data={klineData} height={450} />
        ) : (
          renderEmpty('暂无K线数据，请输入股票代码查询')
        )}
      </Card>

      <Card className={styles.tableCard}>
        <Tabs items={tabItems} />
      </Card>
    </div>
  );
}
